#!/bin/bash

echo "🎯 VR Distribución - Ejemplos de Uso de Scripts"
echo "═══════════════════════════════════════════════"
echo ""
echo "📋 COMANDOS BÁSICOS:"
echo ""
echo "1. 🔍 Ver estado actual:"
echo "   ./quick_switch.sh status"
echo ""
echo "2. 🛠️  Cambiar a desarrollo (para trabajar localmente):"
echo "   ./quick_switch.sh local"
echo ""
echo "3. 📦 Cambiar a producción (antes de subir a S3):"
echo "   ./quick_switch.sh s3"
echo ""
echo "4. 🎭 Ver qué cambiaría sin aplicar:"
echo "   ./quick_switch.sh dry s3"
echo "   ./quick_switch.sh dry local"
echo ""
echo "📝 FLUJO DE TRABAJO TÍPICO:"
echo ""
echo "┌─ Desarrollo ──────────────────────────────────┐"
echo "│ 1. ./quick_switch.sh local                    │"
echo "│ 2. Editar archivos...                         │"
echo "│ 3. Probar en servidor local                   │"
echo "└───────────────────────────────────────────────┘"
echo ""
echo "┌─ Antes de Deploy ─────────────────────────────┐"
echo "│ 1. ./quick_switch.sh dry s3                   │"
echo "│ 2. Verificar cambios                          │"
echo "│ 3. ./quick_switch.sh s3                       │"
echo "│ 4. Subir archivos a S3/servidor               │"
echo "└───────────────────────────────────────────────┘"
echo ""
echo "┌─ Después de Deploy ───────────────────────────┐"
echo "│ 1. ./quick_switch.sh local                    │"
echo "│ 2. Continuar desarrollo...                     │"
echo "└───────────────────────────────────────────────┘"
echo ""
echo "🔧 ALIASES DISPONIBLES:"
echo ""
echo "   Local:      local, dev, development"
echo "   Producción: s3, prod, production"
echo "   Estado:     status, check"
echo ""
echo "💡 TIPS:"
echo ""
echo "   • Siempre usar 'status' para verificar el estado actual"
echo "   • Usar 'dry' para ver cambios antes de aplicarlos"
echo "   • En desarrollo: usar rutas locales (/static/)"
echo "   • En producción: usar rutas S3 (https://...)"
echo ""
echo "🎯 EJEMPLOS RÁPIDOS:"
echo ""
echo "   # Ver estado y cambiar a local"
echo "   ./quick_switch.sh status && ./quick_switch.sh local"
echo ""
echo "   # Verificar cambios a S3 y aplicar"
echo "   ./quick_switch.sh dry s3 && ./quick_switch.sh s3"
echo ""
echo "   # Mostrar esta ayuda"
echo "   ./quick_switch.sh help"
echo ""
