name: CI Deploy VRDISTRIBUCION

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - submitted
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: vrditribucion
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: copy into folder dependencies
        run: |
            mkdir ~/vrdistribucion &&
            cp -r * ~/vrdistribucion &&
            mv ~/vrdistribucion . &&
            ls -la
            ls -la vrdistribucion/

      - name: Prepare SSH to work with the remote server
        run: |
            cd ~ && mkdir .ssh &&
            touch ~/.ssh/known_hosts &&
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key &&
            chmod 600 ~/.ssh/deploy_key

      - name: Publish
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
            host: ${{ secrets.REMOTE_HOST }} # "example.com"
            port: 22 # 22
            user: ${{ secrets.REMOTE_USER }} # "user"
            pass: ${{ secrets.REMOTE_PASS }} # "password"
            connect_timeout: 10s
            scp: |
                "vrdistribucion/*" => /var/www/html/vrdistribucion
            last_ssh: |
              sudo chmod -R 774 /var/www/html/* ; chown -R ubuntu: /var/www/html


      # 2) Ejecutar comandos remotos usando la clave SSH
      - name: Execute remote command
        uses: cross-the-world/ssh-pipeline@v1.2.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: 22
          user: ${{ secrets.REMOTE_USER }}
          privKey: ${{ secrets.SSH_PRIVATE_KEY }}
          script: chmod -R 774 /var/www/html/* ; chown -R www-data:www-data /var/www/html
