name: CI Deploy VRDISTRIBUCION

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - submitted
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: vrditribucion
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: copy into dist folder dependencies
        run: |
          mkdir ~/vrdistribucion &&
          cp -r * ~/vrdistribucion &&
          mv ~/vrdistribucion .

      # 1) Copiar archivos al servidor remoto usando la clave SSH
      - name: Copy to remote using scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "vrdistribucion/*"
          target: "/var/www/html/vrdistribucion/"

      # 2) Ejecutar comandos remotos usando la clave SSH
      - name: Execute remote command
        uses: cross-the-world/ssh-pipeline@v1.2.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: 22
          user: ${{ secrets.REMOTE_USER }}
          privKey: ${{ secrets.SSH_PRIVATE_KEY }}
          script: chmod -R 774 /var/www/html/* ; chown -R www-data:www-data /var/www/html
